server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
      name: gov-service
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      host: 39.104.83.246
      port: 27017
      database: zz_history
      username: admin
      password: ccf@2020
      authentication-database: admin
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLInnoDBDialect
    open-in-view: true

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2


