server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
      name: rbac-service
#  cloud:
#      nacos:
#        discovery:
#          server-addr: 127.0.0.1:8848
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  #数据库索引
  redis:
    database: 0
    host: 39.104.101.137
    port: 6379
    password:
    #连接超时时间
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2
##fastdfs
#fdfs:
#  so-timeout:
#  ###你的IP/
#  web-server-url:
#  connect-timeout:
#  thumb-image:
#    width:
#    height:
#  tracker-list[0]:
#  http:
#    anti_steal_token:
#    secret_key:


